# Generated by Django 2.2.5 on 2019-09-25 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatever', '0002_thing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Waves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavename', models.CharField(max_length=256)),
                ('surfer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='whatever.Surfer')),
            ],
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
